site_name: Subble
repo_url: https://github.com/Subble
pages:
  - Home: index.md
  - Plugins: 
    - Overview: plugins/index.md
    - Quick-Start: plugins/quick-start.md
    - Events: plugins/events.md
theme: readthedocs